RandevuSistemi/Controllers/GirisYapController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using RandevuSistemi.Data;
using RandevuSistemi.Helpers;
using RandevuSistemi.Models;

namespace RandevuSistemi.Controllers
{
    public class GirisYapController : Controller
    {
        private readonly RandevuDBContext _context;
        private readonly CustomExceptionLogger _logger;

        public GirisYapController(RandevuDBContext context, CustomExceptionLogger logger)
        {
            _context = context;
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Index(string email, string password)
        {
            // Kullanıcı doğrulama işlemi
            try
            {
                var kullanici = _context.Kullanicilar
                .FirstOrDefault(k => k.KullaniciMail == email && k.KullaniciSifre == password);

                if (kullanici != null)
                {
                    // Kullanıcı bilgilerini Session'a ekleme
                    HttpContext.Session.SetInt32("KullaniciID", kullanici.KullaniciID);
                    HttpContext.Session.SetInt32("KullaniciTuru", kullanici.KullaniciTuru);

                    // Kullanıcı türüne göre yönlendirme yapabilirsiniz
                    if (kullanici.KullaniciTuru == RolTip.Personel.GetHashCode())
                    {
                        if (kullanici.KullaniciOnay == false)
                        {
                            ModelState.AddModelError("", "Kullanıcı onaylanmamıştır. Lütfen yönetici onayını bekleyin.");
                            return View();
                        }
                        return RedirectToAction("Index", "Yonetim");
                    }
                    else
                    {
                        return RedirectToAction("Profil", "Kullanici");
                    }
                }
                ModelState.AddModelError("", "Geçersiz e-posta veya şifre");
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogException(ex);
                return View();
            }


        }
        public IActionResult Kaydol()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Kaydol(Kullanici kullanici)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var result =_context.Kullanicilar.Where(k => k.KullaniciMail == kullanici.KullaniciMail).FirstOrDefault();
                    if (result != null)
                    {
                        ModelState.AddModelError("", "Bu e-posta adresi zaten kullanılmaktadır.");
                        return View(kullanici);
                    }
                    if (kullanici.KullaniciTuru == RolTip.User.GetHashCode())
                    {
                        kullanici.KullaniciOnay = true;
                    }
                    else
                    {
                        kullanici.KullaniciOnay = false;
                    }
                    _context.Kullanicilar.Add(kullanici);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(kullanici);
            }
            catch (Exception ex)
            {
                _logger.LogException(ex);
                ModelState.AddModelError("", "Bir hata oluştu. Lütfen tekrar deneyin.");
                return View(kullanici);
            }
        }
    }
}

RandevuSistemi/Views/GirisYap/Index.cshtml
@{
    ViewData["Title"] = "Giriş Yap";
}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="/login/fonts/icomoon/style.css">

    <link rel="stylesheet" href="/login/css/owl.carousel.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/login/css/bootstrap.min.css">
    
    <!-- Style -->
    <link rel="stylesheet" href="/login/css/style.css">

    <title>Login #7</title>
  </head>
  <body>
  

  
  <div class="content">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img src="/login/images/undraw_remotely_2j6y.svg" alt="Image" class="img-fluid">
        </div>
        <br>
        <br>
        <br>
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-8">
              <div class="mb-4">
              <h3>Giriş Yap</h3>
              <p class="mb-4">Kayıtlı bir üyeseniz kolaylıkla giriş yapabilirsiniz.</p>
            </div>
            <br>
            <form asp-asp-controller="GirisYap" asp-action="Index" method="post">
              <div class="form-group first">
                <label for="email">Mail Adresi</label>
                <input type="text" class="form-control" id="email" name="email" required >

              </div>
              <div class="form-group last mb-4">
                <label for="password">Şifre</label>
                <input type="password" class="form-control" id="password" name="password" required >
                
              </div>
                  <button type="submit" class="btn btn-primary">Giriş Yap</button> &nbsp;
                  <a href="@Url.Action("Kaydol", "GirisYap")">Kaydol</a>
                  @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                    {
                        <div class="alert alert-danger" role="alert">
                            @ViewBag.ErrorMessage
                        </div>
                    }
            </form>
            </div>
          </div>
          <br>
          <br>
        </div>
        
      </div>
    </div>
  </div>

  
    <script src="/login/js/jquery-3.3.1.min.js"></script>
    <script src="/login/js/popper.min.js"></script>
    <script src="/login/js/bootstrap.min.js"></script>
    <script src="/login/js/main.js"></script>
  </body>
</html>

RandevuSistemi/Views/GirisYap/Kaydol.cshtml
@model RandevuSistemi.Models.Kullanici

@{
    ViewData["Title"] = "Kaydol";
}
@{
    ViewData["Title"] = "Giriş Yap";
}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="/login/fonts/icomoon/style.css">

    <link rel="stylesheet" href="/login/css/owl.carousel.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/login/css/bootstrap.min.css">
    
    <!-- Style -->
    <link rel="stylesheet" href="/login/css/style.css">

    <title>Login #7</title>
  </head>
  <body>
    <br>
    <br>
    <h1>Şimdi Kaydol</h1>
    <br>
    <br>
  
  <div class="container">
        <form asp-action="Kaydol" method="post">
            <div class="form-group">
                <label asp-for="KullaniciAd" class="control-label"></label>
                <input asp-for="KullaniciAd" class="form-control" />
                <span asp-validation-for="KullaniciAd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciSoyad" class="control-label"></label>
                <input asp-for="KullaniciSoyad" class="form-control" />
                <span asp-validation-for="KullaniciSoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciMail" class="control-label"></label>
                <input asp-for="KullaniciMail" class="form-control" />
                <span asp-validation-for="KullaniciMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciSifre" class="control-label"></label>
                <input asp-for="KullaniciSifre" class="form-control" type="password" />
                <span asp-validation-for="KullaniciSifre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KullaniciTuru" class="control-label"></label>
                <select asp-for="KullaniciTuru" class="form-control">
                    <option value="1">Normal Kullanıcı</option>
                    <option value="2">Randevu Oluşturabilen Kullanıcı</option>
                </select>
                <span asp-validation-for="KullaniciTuru" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydol" class="btn btn-primary" />
            </div>
        </form>

<div>
    Zaten bir hesabınız var mı? <a asp-action="Index">Giriş Yap</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}</div>
  </div>

  
    <script src="/login/js/jquery-3.3.1.min.js"></script>
    <script src="/login/js/popper.min.js"></script>
    <script src="/login/js/bootstrap.min.js"></script>
    <script src="/login/js/main.js"></script>
  </body>
</html>